### ISSUE TITLE
Production build doesn't deploy firebase functions 

### ISSUE THREAD

**Issue by lustoykov** [DigitalProductschool/website#129] opened 2019-09-19 09:23 UTC

**Comment by mstockerl** [comment] 2019-09-19 11:38
This is expected behavior as of now. Basically, it should be the same like for the staging branch, but with new tokens. 

Do you (@bhawna333 or @danielbedo) want to try it out or should I do it myself?

**Comment by bhawna333** [comment] 2019-09-19 11:49
> This is expected behavior as of now. Basically, it should be the same like for the staging branch, but with new tokens.
> 
> Do you (@bhawna333 or @danielbedo) want to try it out or should I do it myself?

**Comment by bhawna333** [comment] 2019-09-19 11:51
So I wanted to comment here but ended up closing it by mistake and now I don't know how to unclose it. I wanted to ask @mstockerl  what did you mean by trying it out. I didn't understand the issue well

**Comment by lustoykov** [comment] 2019-09-19 12:17
it's not a blocker for me right now because I deploy them manually

**Comment by mstockerl** [comment] 2019-09-19 12:25
@bhawna333 The idea is to deploy the functions like on staging branch automatically with every commit. For that, we have to add the missing steps in [cloudbuild-prod.yaml](https://github.com/DigitalProductschool/website/blob/master/cloudbuild-prod.yaml) The reference would be [cloudbuild-staging.yaml](https://github.com/DigitalProductschool/website/blob/master/cloudbuild-staging.yaml). 

The only "tricky" part is that we need to create new tokens we can use in the prod env instead of the staging environment. 

Does it make more sense, now?

**Comment by bhawna333** [comment] 2019-09-19 12:39
ah ohkay makes sense. Since I am almost done with my storing tracking data task, maybe I can look into it then and see if I could do it :)

**Closed** 2020-06-18 10:04 UTC
